# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 7596a4db1fbc03f43a99429a191b62fed7df01ee

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка удалить объявление
DELETE {{baseUrl}}/advertisements/41/
Authorization: Token 38d68db2f41370ac27686d4f43001291dd6c2424

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2022-10-01
Content-Type: application/json

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/80/
Content-Type: application/json
Authorization: Token f04826088f1758415bbf661a6772ed3b893792dd

{
  "status": "CLOSED"
}